# Site settings
title: Romana Cloud Native SDN
email: info@romana.io
description: > # this means to ignore newlines until "baseurl:"
  Romana software is awesome!. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: romanaproject
github_username:  romana

# Layout settings
header_type: default	# values [ drawer, default ]
post_type: default	# values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Documentation
    link: www.github.com/romana/docs
  option2:
    name: Fork
    link: www.github.com/romana
  option3:
    name: Try it out
    link: www.github.com/romana/romana

disqus: true
disqus_shortname: 'romana'

# Build settings
markdown: kramdown