#
# This file contains configuration flags to customize your site
#


# Site Title 
title: Romana Cloud Native SDN


description: > # this means to ignore newlines until "baseurl:"
  Romana is a new open source Software Defined Network (SDN) solution specifically designed for Cloud Native applications. Romana allows multi-tenant cloud computing networks for OpenStack, Docker and Kubernetes to be built without encapsulation or a virtual network overlay. Romana networks are less expensive to build, easier to operate and deliver higher performance than networks built using alternative overlay based SDN designs.

# Your website URL (e.g. http://romana.github.io or http://romana.io)
# Used for Sitemap.xml and your RSS feed
url: romana.io

# Homepage URL. Used for links to homepage in templates so all templated don't
# need to be updated when obscure urls used

homepage: earlyaccess.html

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

# Contact/Social Info
email: info@romana.io

# https://twitter.com/romanaproject
twitter_username: romanaproject

# https://github.com/romana
github_username:  romana

# https://www.linkedin.com/in/<linkedin_username>
#linkedin_username:

#https://www.facebook.com/<facebook_profile>
#facebook_profile:

# https://plus.google.com/u/0/<gplus_profile>
# gplus_profile:

# https://instagram.com/<instagram_username>
#instagram_username:

# https://www.pinterest.com/pintrest_username
#pintrest_username:


# Build settings
markdown: kramdown